### ISSUE TITLE
How to export the base box?

### ISSUE THREAD

**Issue by YujieDu** [hh/windows-fromscratch#3]
Thanks for your work! It help me to build the base box in windows7. But I couldn't find how to export the base box after build, validate it.

```
$ bundle exec veewee vbox build 'centos63'
$ bundle exec veewee vbox validate 'centos63'
```

what's next? there is no export parameter if I run this:
    $ bundle exec vagrant basebox export 'centos63'

**Comment by YujieDu** [comment]
how to use this ?
$ vagrant basebox list

C:\Users\Ben\Documents\GitHub\windows-fromscratch>Vagrant basebox list

D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/top.rb:29:in `method_missing': undefined method`winrm' for #Vagrant::Config::Top:0x441318 (NoMethodError)
        from C:/Users/Ben/Documents/GitHub/windows-fromscratch/Vagrantfile:6:in`block in <top (required)>' 
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/loader.rb:83:in`call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/loader.rb:83:in `block (2 levels) in load'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/loader.rb:79:in`each'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/loader.rb:79:in `block in load'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/loader.rb:76:in`each'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/config/loader.rb:76:in `load'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/environment.rb:387:in`block in load_config!'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/environment.rb:392:in `call'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/environment.rb:392:in`load_config!'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/environment.rb:327:in `load!'
        from D:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/bin/vagrant:40:in`<top (required)>'
        from D:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `load'
        from D:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in`<main>'
